version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_planning_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - myplanningnetwork

  app:
    build: .
    container_name: my_planning_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    env_file:
      - .env
    networks:
      - myplanningnetwork

volumes:
  postgres_data:

networks:
  myplanningnetwork:
